/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminCommentariesRouteImport } from './routes/admin.commentaries'
import { Route as AdminEntriesRouteImport } from './routes/admin.entries'
import { Route as AdminPathsRouteImport } from './routes/admin.paths'
import { Route as AdminRebuttalsRouteImport } from './routes/admin.rebuttals'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminTaxonomyRouteImport } from './routes/admin.taxonomy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentariesRoute = AdminCommentariesRouteImport.update({
  id: '/commentaries',
  path: '/commentaries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntriesRoute = AdminEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPathsRoute = AdminPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRebuttalsRoute = AdminRebuttalsRouteImport.update({
  id: '/rebuttals',
  path: '/rebuttals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/commentaries': typeof AdminCommentariesRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/rebuttals': typeof AdminRebuttalsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/commentaries': typeof AdminCommentariesRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/rebuttals': typeof AdminRebuttalsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/commentaries': typeof AdminCommentariesRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/paths': typeof AdminPathsRoute
  '/admin/rebuttals': typeof AdminRebuttalsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/activity'
    | '/admin/commentaries'
    | '/admin/entries'
    | '/admin/paths'
    | '/admin/rebuttals'
    | '/admin/requests'
    | '/admin/sources'
    | '/admin/taxonomy'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activity'
    | '/admin/commentaries'
    | '/admin/entries'
    | '/admin/paths'
    | '/admin/rebuttals'
    | '/admin/requests'
    | '/admin/sources'
    | '/admin/taxonomy'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/activity'
    | '/admin/commentaries'
    | '/admin/entries'
    | '/admin/paths'
    | '/admin/rebuttals'
    | '/admin/requests'
    | '/admin/sources'
    | '/admin/taxonomy'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commentaries': {
      id: '/admin/commentaries'
      path: '/commentaries'
      fullPath: '/admin/commentaries'
      preLoaderRoute: typeof AdminCommentariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entries': {
      id: '/admin/entries'
      path: '/entries'
      fullPath: '/admin/entries'
      preLoaderRoute: typeof AdminEntriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paths': {
      id: '/admin/paths'
      path: '/paths'
      fullPath: '/admin/paths'
      preLoaderRoute: typeof AdminPathsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rebuttals': {
      id: '/admin/rebuttals'
      path: '/rebuttals'
      fullPath: '/admin/rebuttals'
      preLoaderRoute: typeof AdminRebuttalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminCommentariesRoute: typeof AdminCommentariesRoute
  AdminEntriesRoute: typeof AdminEntriesRoute
  AdminPathsRoute: typeof AdminPathsRoute
  AdminRebuttalsRoute: typeof AdminRebuttalsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminCommentariesRoute: AdminCommentariesRoute,
  AdminEntriesRoute: AdminEntriesRoute,
  AdminPathsRoute: AdminPathsRoute,
  AdminRebuttalsRoute: AdminRebuttalsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
